"use client";

import { useState } from "react";

interface StepFormProps { selectedLocation: string; locationId: string; selectedDate: string; selectedTime: string; }
export default function StepForm({ selectedLocation, locationId, selectedDate, selectedTime }: StepFormProps) {
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [status, setStatus] = useState(""); const isFormValid = name.trim().length > 2 && phone.replace(/\D/g, "").length >= 9;
  async function handleBooking() { if (!isFormValid) return; setLoading(true); setStatus(""); try { const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ locationId, date: selectedDate, time: selectedTime, name, phone, email, message, source: "main-site" }) }); const data = await response.json(); setStatus(data.message ?? (data.success ? "Gotowe. ❤️ Aleksandra otrzymała Twoją rezerwację." : "Nie udało się zapisać rezerwacji.")); } catch { setStatus("Nie udało się zapisać rezerwacji. Spróbuj ponownie za chwilę. ❤️"); } finally { setLoading(false); } }
  const displayDate = new Date(`${selectedDate}T12:00:00`).toLocaleDateString("pl-PL", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  return <section id="step-form" className="mt-12 rounded-3xl border border-[#EFE8DD] bg-white p-8 shadow-xl"><h2 className="text-2xl font-bold text-[#4B4338]">Dane do kontaktu</h2><p className="mt-2 text-gray-600">Wypełnij formularz, a Aleksandra skontaktuje się z Tobą w celu potwierdzenia terminu.</p><div className="mt-6 rounded-2xl border border-[#E8E1D5] bg-[#F8F5F0] p-5"><h3 className="mb-3 text-lg font-semibold text-[#4B4338]">Wybrany termin konsultacji</h3><div className="space-y-2 text-[#4B4338]"><p><span className="font-semibold">Lokalizacja:</span> {selectedLocation}</p><p><span className="font-semibold">Termin:</span> {displayDate}</p><p><span className="font-semibold">Godzina:</span> {selectedTime}</p></div></div><div className="mt-8 space-y-5"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Imię i nazwisko *" className="w-full rounded-xl border border-gray-300 px-4 py-3" /><input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Telefon *" className="w-full rounded-xl border border-gray-300 px-4 py-3" /><input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="E-mail" className="w-full rounded-xl border border-gray-300 px-4 py-3" /><textarea rows={5} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Krótka wiadomość (opcjonalnie)" className="w-full rounded-xl border border-gray-300 px-4 py-3" /><button type="button" onClick={handleBooking} disabled={loading || !isFormValid} className="w-full rounded-xl bg-[#6D7A62] py-4 text-lg font-semibold text-white disabled:cursor-not-allowed disabled:bg-gray-400">{loading ? "Wysyłanie…" : "Umów wizytę"}</button>{status && <p aria-live="polite" className="text-sm text-[#55624D]">{status}</p>}<p className="text-sm text-gray-500">* Pola oznaczone gwiazdką są obowiązkowe.</p></div></section>;
}
