import type { VisitReflection } from "../../domain";

export default function PatientEmotionJourney({ reflections }: { reflections: VisitReflection[] }) {
  return <section className="rounded-3xl border border-[#E5E1D8] bg-white p-6 shadow-[0_12px_35px_rgba(45,71,57,0.06)]"><div><p className="text-sm text-gray-500">Prywatne obserwacje po spotkaniach</p><h2 className="mt-1 font-bold text-[#2D4739]">🌿 Przebieg terapii</h2></div><EmotionJourneyChart reflections={reflections} />{reflections.length === 0 ? <p className="mt-6 rounded-2xl bg-[#F8F5F0] px-4 py-6 text-center text-sm text-gray-500">Brak zapisanych refleksji po spotkaniach.</p> : <div className="mt-6 space-y-4">{reflections.map((reflection) => <article key={reflection.id} className="rounded-2xl bg-[#F8F5F0] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold text-[#2D4739]">Refleksja po spotkaniu</h3><p className="mt-1 text-xs text-gray-500">{new Date(reflection.created_at).toLocaleDateString("pl-PL", { day: "numeric", month: "long", year: "numeric" })}</p></div><div className="flex gap-2 text-xs font-semibold"><Metric label="Nastrój" value={reflection.mood_level} /><Metric label="Energia" value={reflection.energy_level} /><Metric label="Zaangażowanie" value={reflection.engagement_level} /></div></div>{reflection.reflection && <p className="mt-4 whitespace-pre-wrap border-t border-[#E5E1D8] pt-4 text-sm text-gray-700">{reflection.reflection}</p>}</article>)}</div>}</section>;
}

function EmotionJourneyChart({ reflections }: { reflections: VisitReflection[] }) { return <div className="mt-6 rounded-2xl border border-dashed border-[#D5DCCF] bg-[#EEF1EB] px-5 py-8 text-center text-sm text-[#55624D]"><p className="font-semibold">Wykres Emotion Journey</p><p className="mt-1">{reflections.length} zapisanych obserwacji</p><p className="mt-3 text-xs">TODO: wizualizacja zmian nastroju, energii i zaangażowania w czasie — bez biblioteki na obecnym etapie.</p></div>; }

function Metric({ label, value }: { label: string; value: number }) { return <span className="rounded-lg bg-white px-2 py-1 text-[#2D4739]">{label}: {value}/5</span>; }
