"use client";

import { useMemo, useState } from "react";
import { Banknote, CalendarCheck2, CalendarX2, MapPin } from "lucide-react";
import type { PracticePeriodStatistics, PracticeStatisticsData } from "../../services/practiceStatisticsService";

export default function PracticeStatistics({ data }: { data: PracticeStatisticsData }) {
  const [year, setYear] = useState(data.currentYear);
  const [month, setMonth] = useState(data.currentMonth);
  const selectedYear = data.years.find((item) => item.year === year) ?? data.years[0];
  const selectedMonth = selectedYear?.months[month - 1] ?? emptyPeriod(`${year}-${month}`, "Wybrany miesiąc");
  const leadingLocation = useMemo(() => getLeadingLocation(selectedMonth), [selectedMonth]);

  return <div className="space-y-6">
    {!data.financeAvailable && <p className="rounded-2xl border border-[#E8D39D] bg-[#FFF9E9] px-5 py-4 text-sm text-[#725C28]">Liczby wizyt działają. Kwoty pojawią się po uruchomieniu migracji <strong>add_booking_visit_fee.sql</strong>.</p>}
    <section className="rounded-3xl border border-[#E5E1D8] bg-white p-5 shadow-[0_12px_35px_rgba(45,71,57,0.06)] sm:p-7">
      <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[#6D7A62]">Wybrany okres</p><h2 className="mt-1 text-2xl font-bold text-[#2D4739]">{selectedMonth.label}</h2><p className="mt-2 text-sm text-gray-600">Statystyki nie zawierają nazwisk ani danych kontaktowych pacjentów.</p></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold text-[#2D4739]">Rok<select value={year} onChange={(event) => setYear(Number(event.target.value))} className={selectClass}>{data.years.map((item) => <option key={item.year}>{item.year}</option>)}</select></label><label className="text-sm font-semibold text-[#2D4739]">Miesiąc<select value={month} onChange={(event) => setMonth(Number(event.target.value))} className={selectClass}>{selectedYear?.months.map((item, index) => <option key={item.key} value={index + 1}>{monthName(item.label)}</option>)}</select></label></div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={CalendarCheck2} label="Odbyte wizyty" value={String(selectedMonth.completedVisits)} detail={`${selectedMonth.completionRate}% wszystkich`} /><MetricCard icon={CalendarX2} label="Odwołane" value={String(selectedMonth.cancelledVisits)} detail={`${selectedMonth.cancellationRate}% wszystkich`} /><MetricCard icon={Banknote} label="Kwota odbytych" value={data.financeAvailable ? formatCurrency(selectedMonth.completedRevenue) : "—"} detail={data.financeAvailable ? `${selectedMonth.completedWithoutFee} odbytych bez kwoty` : "Po uruchomieniu SQL"} /><MetricCard icon={MapPin} label="Najczęściej" value={leadingLocation.label} detail={`${leadingLocation.share}% nieodwołanych wizyt`} /></div>
    </section>

    <div className="grid gap-6 xl:grid-cols-2">
      <LocationBreakdown period={selectedMonth} />
      <section className="rounded-3xl border border-[#E5E1D8] bg-white p-5 shadow-[0_12px_35px_rgba(45,71,57,0.06)] sm:p-7"><div className="flex items-center gap-3"><Banknote className="text-[#6D7A62]" size={22} /><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[#6D7A62]">Kwoty orientacyjne</p><h2 className="text-xl font-bold text-[#2D4739]">Podsumowanie miesiąca</h2></div></div><div className="mt-5 space-y-3"><SummaryRow label="Odbyte wizyty" value={data.financeAvailable ? formatCurrency(selectedMonth.completedRevenue) : "—"} /><SummaryRow label="Zaplanowane, nieodwołane" value={data.financeAvailable ? formatCurrency(selectedMonth.scheduledValue) : "—"} /><SummaryRow label="Wizyty z wpisaną kwotą" value={data.financeAvailable ? `${selectedMonth.feeCoverageRate}%` : "—"} /><SummaryRow label="Łącznie wpisów w miesiącu" value={String(selectedMonth.totalVisits)} /></div><p className="mt-5 rounded-2xl bg-[#F8F5F0] p-4 text-xs leading-5 text-[#55624D]">To pomocniczy wykaz zarządczy. Nie zastępuje ewidencji księgowej, faktur ani potwierdzeń płatności.</p></section>
    </div>

    {selectedYear && <YearOverview year={selectedYear} financeAvailable={data.financeAvailable} />}
  </div>;
}

function MetricCard({ icon: Icon, label, value, detail }: { icon: typeof CalendarCheck2; label: string; value: string; detail: string }) { return <article className="rounded-2xl bg-[#F8F5F0] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm text-gray-500">{label}</p><Icon size={18} className="text-[#6D7A62]" aria-hidden="true" /></div><p className="mt-3 break-words text-2xl font-bold text-[#2D4739]">{value}</p><p className="mt-1 text-xs text-gray-500">{detail}</p></article>; }

function LocationBreakdown({ period }: { period: PracticePeriodStatistics }) { const total = period.locations.zielinscy + period.locations.arthro + period.locations.other; return <section className="rounded-3xl border border-[#E5E1D8] bg-white p-5 shadow-[0_12px_35px_rgba(45,71,57,0.06)] sm:p-7"><div className="flex items-center gap-3"><MapPin className="text-[#6D7A62]" size={22} /><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[#6D7A62]">Gabinety</p><h2 className="text-xl font-bold text-[#2D4739]">Gdzie odbywają się zapisy?</h2></div></div>{total === 0 ? <p className="mt-5 rounded-2xl bg-[#F8F5F0] p-5 text-sm text-gray-500">Brak nieodwołanych wizyt w tym okresie.</p> : <div className="mt-6 space-y-5"><LocationBar label="Centrum Zielińscy Premium" count={period.locations.zielinscy} share={period.locations.zielinscyShare} /><LocationBar label="Arthro Cure Clinic" count={period.locations.arthro} share={period.locations.arthroShare} />{period.locations.other > 0 && <LocationBar label="Pozostałe / starsze wpisy" count={period.locations.other} share={period.locations.otherShare} />}</div>}</section>; }

function LocationBar({ label, count, share }: { label: string; count: number; share: number }) { return <div><div className="flex items-center justify-between gap-3 text-sm"><span className="font-semibold text-[#2D4739]">{label}</span><span className="text-gray-500">{count} · {share}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#EEF1EB]"><div className="h-full rounded-full bg-[#6D7A62]" style={{ width: `${share}%` }} /></div></div>; }

function YearOverview({ year, financeAvailable }: { year: PracticeStatisticsData["years"][number]; financeAvailable: boolean }) { return <section className="rounded-3xl border border-[#E5E1D8] bg-white p-5 shadow-[0_12px_35px_rgba(45,71,57,0.06)] sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-[#6D7A62]">Perspektywa roczna</p><h2 className="mt-1 text-2xl font-bold text-[#2D4739]">Rok {year.year}</h2></div><p className="text-sm text-gray-500">{year.completedVisits} odbytych · {year.cancelledVisits} odwołanych{financeAvailable ? ` · ${formatCurrency(year.completedRevenue)}` : ""}</p></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-[#E5E1D8] text-xs uppercase tracking-[0.08em] text-gray-500"><th className="px-3 py-3">Miesiąc</th><th className="px-3 py-3">Wszystkie</th><th className="px-3 py-3">Odbyte</th><th className="px-3 py-3">Odwołane</th><th className="px-3 py-3">Skuteczność</th><th className="px-3 py-3">Kwota odbytych</th></tr></thead><tbody>{year.months.map((item) => <tr key={item.key} className="border-b border-[#F0EDE7] last:border-0"><td className="px-3 py-3 font-semibold text-[#2D4739]">{monthName(item.label)}</td><td className="px-3 py-3">{item.totalVisits}</td><td className="px-3 py-3">{item.completedVisits}</td><td className="px-3 py-3">{item.cancelledVisits}</td><td className="px-3 py-3">{item.completionRate}%</td><td className="px-3 py-3">{financeAvailable ? formatCurrency(item.completedRevenue) : "—"}</td></tr>)}</tbody></table></div></section>; }

function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 rounded-xl bg-[#F8F5F0] px-4 py-3"><span className="text-sm text-gray-600">{label}</span><strong className="text-right text-[#2D4739]">{value}</strong></div>; }
function getLeadingLocation(period: PracticePeriodStatistics) { const options = [{ label: "Zielińscy", count: period.locations.zielinscy, share: period.locations.zielinscyShare }, { label: "Arthro", count: period.locations.arthro, share: period.locations.arthroShare }, { label: "Pozostałe", count: period.locations.other, share: period.locations.otherShare }]; const leading = options.sort((left, right) => right.count - left.count)[0]; return leading.count > 0 ? leading : { label: "Brak danych", count: 0, share: 0 }; }
function emptyPeriod(key: string, label: string): PracticePeriodStatistics { return { key, label, totalVisits: 0, completedVisits: 0, cancelledVisits: 0, otherVisits: 0, completionRate: 0, cancellationRate: 0, completedRevenue: 0, scheduledValue: 0, completedWithoutFee: 0, feeCoverageRate: 0, locations: { zielinscy: 0, arthro: 0, other: 0, zielinscyShare: 0, arthroShare: 0, otherShare: 0 } }; }
function monthName(label: string) { return label.replace(/\s+\d{4}$/, ""); }
function formatCurrency(value: number) { return new Intl.NumberFormat("pl-PL", { style: "currency", currency: "PLN" }).format(value); }
const selectClass = "mt-2 w-full min-w-32 rounded-xl border border-[#D5DCCF] bg-white px-3 py-2.5 text-[#263E32] outline-none focus:border-[#6D7A62]";
