-- Run manually in Supabase only after the Site Pulse MVP and privacy scope are accepted.
-- This migration stores anonymous, short-lived journey identifiers only.
-- It intentionally does not store IP addresses, user agents, device data,
-- booking IDs, patient IDs or form contents.

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_id uuid not null unique,
  journey_id uuid not null,
  event_type text not null check (event_type in (
    'page_view',
    'section_view',
    'booking_opened',
    'booking_form_started',
    'booking_completed'
  )),
  page_key text not null check (page_key in ('home', 'arthro', 'zielinscy')),
  section_key text null check (section_key is null or section_key in ('hero', 'about', 'services', 'booking', 'contact')),
  source_key text not null default 'direct' check (char_length(source_key) between 1 and 64),
  utm_source text null check (utm_source is null or char_length(utm_source) between 1 and 64),
  utm_medium text null check (utm_medium is null or char_length(utm_medium) between 1 and 64),
  utm_campaign text null check (utm_campaign is null or char_length(utm_campaign) between 1 and 64)
);

create index if not exists site_analytics_events_occurred_at_idx
  on public.site_analytics_events (occurred_at desc);
create index if not exists site_analytics_events_type_occurred_at_idx
  on public.site_analytics_events (event_type, occurred_at desc);
create index if not exists site_analytics_events_page_occurred_at_idx
  on public.site_analytics_events (page_key, occurred_at desc);
create index if not exists site_analytics_events_journey_occurred_at_idx
  on public.site_analytics_events (journey_id, occurred_at desc);

create table if not exists public.site_analytics_presence (
  journey_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  page_key text not null check (page_key in ('home', 'arthro', 'zielinscy')),
  section_key text null check (section_key is null or section_key in ('hero', 'about', 'services', 'booking', 'contact')),
  source_key text not null default 'direct' check (char_length(source_key) between 1 and 64),
  check (last_seen_at >= first_seen_at)
);

create index if not exists site_analytics_presence_last_seen_at_idx
  on public.site_analytics_presence (last_seen_at desc);

alter table public.site_analytics_events enable row level security;
alter table public.site_analytics_presence enable row level security;

-- Browser clients must never access analytics tables directly.
-- The application writes through validated server Route Handlers only.
revoke all on table public.site_analytics_events from anon, authenticated;
revoke all on table public.site_analytics_presence from anon, authenticated;
revoke all on sequence public.site_analytics_events_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.site_analytics_events to service_role;
grant select, insert, update, delete on table public.site_analytics_presence to service_role;
grant usage, select on sequence public.site_analytics_events_id_seq to service_role;

-- Recommended retention, to be scheduled separately only after approval:
-- delete from public.site_analytics_presence where last_seen_at < now() - interval '24 hours';
-- delete from public.site_analytics_events where occurred_at < now() - interval '30 days';
