-- Run manually in Supabase. This migration intentionally does not seed working hours.
-- Configure confirmed rules for each location after execution.

alter table public.bookings add column if not exists location_id text;
alter table public.bookings add column if not exists source text;

update public.bookings
set location_id = case
  when lower(coalesce(location, '')) like '%nowa wieś rzeczna%' or lower(coalesce(location, '')) like '%zielińscy%' then 'nowa-wies-rzeczna'
  when lower(coalesce(location, '')) like '%arthro%' then 'arthro-cure-clinic'
  else location_id
end
where location_id is null;

alter table public.bookings
  add constraint bookings_location_id_check
  check (location_id is null or location_id in ('nowa-wies-rzeczna', 'arthro-cure-clinic')) not valid;

create table if not exists public.availability_rules (
  id bigint generated by default as identity primary key,
  location_id text not null check (location_id in ('nowa-wies-rzeczna', 'arthro-cure-clinic')),
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_duration_minutes integer not null check (slot_duration_minutes between 5 and 240),
  is_active boolean not null default true,
  valid_from date null,
  valid_to date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time),
  check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

create index if not exists availability_rules_location_weekday_idx on public.availability_rules(location_id, weekday) where is_active;

create table if not exists public.availability_exceptions (
  id bigint generated by default as identity primary key,
  location_id text not null check (location_id in ('nowa-wies-rzeczna', 'arthro-cure-clinic')),
  date date not null,
  kind text not null check (kind in ('available', 'unavailable')),
  start_time time null,
  end_time time null,
  slot_duration_minutes integer null check (slot_duration_minutes between 5 and 240),
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((start_time is null and end_time is null) or (start_time is not null and end_time is not null and end_time > start_time)),
  check (kind <> 'available' or slot_duration_minutes is not null)
);

create index if not exists availability_exceptions_location_date_idx on public.availability_exceptions(location_id, date);

-- Inspect existing conflicts before executing this index. It is the atomic double-booking guard.
-- select location_id, visit_date, visit_time, count(*) from public.bookings
-- where location_id is not null group by 1,2,3 having count(*) > 1;
create unique index if not exists bookings_location_id_date_time_unique_idx
  on public.bookings(location_id, visit_date, visit_time)
  where location_id is not null;

create index if not exists bookings_source_idx on public.bookings(source);

-- Required input after migration: insert only confirmed working hours.
-- Do not add a Tuesday rule for nowa-wies-rzeczna.
-- Example shape only (do not execute until hours are confirmed):
-- insert into public.availability_rules (location_id, weekday, start_time, end_time, slot_duration_minutes)
-- values ('nowa-wies-rzeczna', 1, 'CONFIRMED_START', 'CONFIRMED_END', CONFIRMED_MINUTES);
