-- Immutable audit trail for account terms/privacy acknowledgements.
-- Registration still works before this migration, but this table should be
-- installed before public promotion so acceptance evidence is server-owned.

begin;

create table if not exists public.member_legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null check (char_length(terms_version) between 1 and 32),
  privacy_notice_version text not null check (char_length(privacy_notice_version) between 1 and 32),
  adult_or_guardian_confirmed boolean not null,
  accepted_at timestamptz not null default now(),
  source text not null default 'web_registration' check (source in ('web_registration', 'manual_reacceptance')),
  unique (user_id, terms_version, privacy_notice_version)
);

create index if not exists member_legal_acceptances_user_date_idx
  on public.member_legal_acceptances (user_id, accepted_at desc);

alter table public.member_legal_acceptances enable row level security;

-- No browser role receives direct access. Only the trigger and trusted
-- service-role administration may read/write the audit trail.
revoke all on table public.member_legal_acceptances from public, anon, authenticated;
grant select, insert, update, delete on table public.member_legal_acceptances to service_role;
grant usage, select on sequence public.member_legal_acceptances_id_seq to service_role;

create or replace function public.capture_member_legal_acceptance()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  accepted_terms text := nullif(trim(new.raw_user_meta_data ->> 'accepted_terms_version'), '');
  privacy_version text := nullif(trim(new.raw_user_meta_data ->> 'privacy_notice_version'), '');
  adult_confirmed boolean := coalesce((new.raw_user_meta_data ->> 'adult_or_guardian_confirmed')::boolean, false);
begin
  if accepted_terms is null or privacy_version is null or adult_confirmed is not true then
    return new;
  end if;

  insert into public.member_legal_acceptances (
    user_id,
    terms_version,
    privacy_notice_version,
    adult_or_guardian_confirmed,
    accepted_at,
    source
  ) values (
    new.id,
    left(accepted_terms, 32),
    left(privacy_version, 32),
    true,
    now(),
    'web_registration'
  ) on conflict (user_id, terms_version, privacy_notice_version) do nothing;

  return new;
exception
  when invalid_text_representation then
    -- Malformed user-controlled metadata must never break auth sign-up.
    return new;
end;
$$;

revoke all on function public.capture_member_legal_acceptance() from public, anon, authenticated;

drop trigger if exists on_auth_user_created_legal_acceptance on auth.users;
create trigger on_auth_user_created_legal_acceptance
  after insert on auth.users
  for each row execute function public.capture_member_legal_acceptance();

commit;
