"use client";

import { BookOpen, Brain, CheckSquare, Heart, Lightbulb, Target } from "lucide-react";
import Link from "next/link";
import type { VisitBriefData } from "../services/visitBriefService";

export default function PsychOLKAAssistantCard({ patientId, brief }: { patientId: string; brief: VisitBriefData | null }) {
  if (!brief) return null;
  const goals = [brief.currentPlan?.main_goal, brief.currentPlan?.secondary_goal].filter((goal): goal is string => Boolean(goal?.trim()));
  const questions = brief.pinnedReflections.filter((card) => card.category === "next_questions" && card.content.trim());
  const latestMaterial = brief.visitMaterials[0] ?? null;
  const recent = [{ label: "Ostatnia notatka", value: brief.latestNote?.content ?? "" }, { label: "Ostatnie zadanie", value: brief.tasks[0]?.title ?? "" }, { label: "Ostatni materiał", value: latestMaterial?.title ?? "" }].filter((item) => item.value.trim());
  const timeline = brief.timelineEvents.slice(0, 3);
  return <section className="rounded-3xl border border-[#D5DCCF] bg-[#FCFDFB] p-5 shadow-[0_12px_35px_rgba(45,71,57,0.05)]"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-[#55624D]">PsychOLKA Assistant</p><h2 className="mt-1 text-xl font-bold text-[#2D4739]">Najważniejsze przed spotkaniem</h2></div><Link href={`/panel/patients/${patientId}?tab=history`} className="shrink-0 text-sm font-semibold text-[#6D7A62] hover:text-[#2D4739]">Otwórz pełną historię</Link></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{goals.length > 0 && <CompactSection icon={Target} title="Cele wizyty" items={goals} />}{brief.homeworkTasks.length > 0 && <CompactSection icon={CheckSquare} title="Otwarte zadania" items={brief.homeworkTasks.slice(0, 2).map((task) => task.title)} />}{brief.visitMaterials.length > 0 && <CompactSection icon={BookOpen} title="Materiały" items={brief.visitMaterials.slice(0, 2).map((material) => material.title)} />}{brief.pinnedMemory.length > 0 && <CompactSection icon={Brain} title="Przypięte Memory" items={brief.pinnedMemory.slice(0, 2).map((item) => item.title)} />}{timeline.length > 0 && <CompactSection icon={Heart} title="Relationship Timeline" items={timeline.map((event) => event.title)} />}{questions.length > 0 && <CompactSection icon={Lightbulb} title="Dzisiaj warto zapytać" items={questions.slice(0, 2).map((question) => question.content)} />}{recent.length > 0 && <section className="rounded-2xl bg-white p-4 lg:col-span-2"><h3 className="text-sm font-semibold text-[#2D4739]">Ostatnie zmiany</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{recent.map((item) => <div key={item.label}><p className="text-xs text-[#6D7A62]">{item.label}</p><p className="mt-1 line-clamp-2 text-sm text-gray-700">{item.value}</p></div>)}</div></section>}</div><section className="mt-4 rounded-2xl border border-dashed border-[#D5DCCF] bg-[#EEF1EB] p-4"><p className="text-sm font-semibold text-[#2D4739]">AI Assistant</p><p className="mt-1 text-sm text-[#55624D]">W przyszłości tutaj pojawią się inteligentne podpowiedzi.</p><p className="mt-2 text-xs text-[#55624D]">TODO: wyłącznie pomocnicze podsumowania zapisanych danych — bez diagnoz i rozpoznań.</p></section></section>;
}

function CompactSection({ icon: Icon, title, items }: { icon: typeof Target; title: string; items: string[] }) { return <section className="rounded-2xl bg-white p-4"><div className="flex items-center gap-2 text-[#6D7A62]"><Icon size={17} aria-hidden="true" /><h3 className="text-sm font-semibold text-[#2D4739]">{title}</h3></div><ul className="mt-3 space-y-1.5">{items.map((item, index) => <li key={`${item}-${index}`} className="line-clamp-2 text-sm text-gray-700">{item}</li>)}</ul></section>; }
