"use client";

import { Brain, CheckSquare, Clock3, Play, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Visit } from "../domain";
import type { VisitBriefData } from "../services/visitBriefService";
import VisitKnowledgeMaterials from "./VisitKnowledgeMaterials";

export default function SmartVisitPreparation({ visit, brief }: { visit: Visit; brief: VisitBriefData | null }) {
  const router = useRouter(); const [checked, setChecked] = useState({ note: false, homework: false, materials: false });
  const previousVisits = Math.max((brief?.visitNumber ?? 1) - 1, 0);
  const lastVisit = brief?.previousVisit;
  const lastTask = brief?.homeworkTasks[0];
  return <section className="rounded-3xl border border-[#D5DCCF] bg-[#FCFDFB] p-5 shadow-[0_12px_35px_rgba(45,71,57,0.05)]"><div className="flex items-center gap-3"><span className="rounded-2xl bg-[#EEF1EB] p-3 text-[#6D7A62]"><Sparkles size={20} aria-hidden="true" /></span><div><p className="text-sm text-[#55624D]">Smart Visit Preparation</p><h2 className="font-bold text-[#2D4739]">Przygotowanie do wizyty</h2></div></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><PreparationCard reason={brief?.firstReason ?? visit.message ?? "Brak wiadomości pozostawionej podczas rejestracji."} previousVisits={previousVisits} lastVisit={lastVisit ? `${new Date(`${lastVisit.visit_date}T00:00:00`).toLocaleDateString("pl-PL")} · ${brief?.latestNote?.content ?? "Brak krótkiej notatki."}` : "To pierwsza wizyta lub brak historii."} goal={brief?.currentPlan?.main_goal || "Cel terapii nie został jeszcze zapisany."} task={lastTask ? `${lastTask.title}${lastTask.description ? ` · ${lastTask.description}` : ""}` : "Brak aktywnego zadania domowego."} /><Memory memory={brief?.pinnedMemory ?? []} /><RelationshipTimeline events={brief?.timelineEvents ?? []} /><VisitKnowledgeMaterials visit={visit} /><Checklist checked={checked} onChange={setChecked} /><div className="space-y-5"><section className="rounded-2xl bg-[#F8F5F0] p-5"><div className="flex items-center gap-3"><Brain size={19} className="text-[#6D7A62]" aria-hidden="true" /><h3 className="font-bold text-[#2D4739]">Sugestie PsychOLI</h3></div><p className="mt-3 text-sm text-gray-600">W przyszłości tutaj pojawią się podpowiedzi wygenerowane na podstawie wcześniejszych danych.</p><p className="mt-3 text-xs text-gray-500">TODO: AI może porządkować wcześniej zapisane informacje, bez diagnoz i sugestii rozpoznań.</p></section><button type="button" onClick={() => router.push(`/panel/visits/${visit.id}/session`)} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#6D7A62] px-4 py-3.5 font-semibold text-white transition hover:bg-[#58644F]"><Play size={18} aria-hidden="true" />Rozpocznij wizytę</button></div></div></section>;
}

function PreparationCard({ reason, previousVisits, lastVisit, goal, task }: { reason: string; previousVisits: number; lastVisit: string; goal: string; task: string }) { return <section className="rounded-2xl bg-white p-5"><h3 className="font-bold text-[#2D4739]">Najważniejsze informacje</h3><div className="mt-4 space-y-4 text-sm"><Item label="Powód zgłoszenia" value={reason} /><Item label="Poprzednie wizyty" value={String(previousVisits)} /><Item label="Ostatnia wizyta" value={lastVisit} /><Item label="Najbliższy cel terapii" value={goal} /><Item label="Ostatnie zadanie domowe" value={task} /></div></section>; }
function Item({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold text-[#6D7A62]">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-gray-700">{value}</p></div>; }
function Memory({ memory }: { memory: VisitBriefData["pinnedMemory"] }) { return <section className="rounded-2xl bg-white p-5"><div className="flex items-center gap-2"><Brain size={19} className="text-[#6D7A62]" aria-hidden="true" /><h3 className="font-bold text-[#2D4739]">PsychOLKA Memory</h3></div>{memory.length === 0 ? <Empty>Brak przypiętych wpisów Memory.</Empty> : <div className="mt-4 space-y-3">{memory.map((item) => <article key={item.id} className="rounded-xl bg-[#F8F5F0] p-3"><p className="text-xs font-semibold text-[#6D7A62]">{item.category}</p><p className="mt-1 text-sm font-semibold text-[#2D4739]">{item.title}</p>{item.content && <p className="mt-1 text-sm text-gray-700">{item.content}</p>}</article>)}</div>}</section>; }
function RelationshipTimeline({ events }: { events: VisitBriefData["timelineEvents"] }) { return <section className="rounded-2xl bg-white p-5"><div className="flex items-center gap-2"><Clock3 size={19} className="text-[#6D7A62]" aria-hidden="true" /><h3 className="font-bold text-[#2D4739]">Relationship Timeline</h3></div>{events.length === 0 ? <Empty>Najważniejsze wydarzenia pojawią się tutaj.</Empty> : <ol className="mt-4 space-y-3 border-l border-[#D5DCCF] pl-4">{events.map((event) => <li key={event.id} className="relative"><span className="absolute -left-[21px] top-1.5 h-2.5 w-2.5 rounded-full bg-[#6D7A62]" /><p className="text-xs text-gray-500">{new Date(event.created_at).toLocaleDateString("pl-PL")}</p><p className="mt-1 text-sm font-semibold text-[#2D4739]">{event.title}</p><p className="mt-1 text-sm text-gray-600">{event.description || "Ważny etap współpracy."}</p></li>)}</ol>}</section>; }
function Checklist({ checked, onChange }: { checked: { note: boolean; homework: boolean; materials: boolean }; onChange: (value: { note: boolean; homework: boolean; materials: boolean }) => void }) { const entries: Array<[keyof typeof checked, string]> = [["note", "Przeczytano poprzednią notatkę"], ["homework", "Sprawdzono zadanie domowe"], ["materials", "Otworzono materiały"]]; return <section className="rounded-2xl bg-white p-5"><div className="flex items-center gap-2"><CheckSquare size={19} className="text-[#6D7A62]" aria-hidden="true" /><h3 className="font-bold text-[#2D4739]">Checklist przed spotkaniem</h3></div><div className="mt-4 space-y-3">{entries.map(([key, label]) => <label key={key} className="flex cursor-pointer items-center gap-3 text-sm text-gray-700"><input type="checkbox" checked={checked[key]} onChange={(event) => onChange({ ...checked, [key]: event.target.checked })} className="h-4 w-4 accent-[#6D7A62]" />{label}</label>)}</div><p className="mt-4 text-xs text-gray-500">Lista jest zapisywana wyłącznie lokalnie w tej sesji przeglądarki.</p></section>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="mt-4 rounded-xl bg-[#F8F5F0] p-4 text-sm text-gray-600">{children}</p>; }
