"use client";

import { BookOpen, Pin, Plus, X } from "lucide-react";
import { useEffect, useMemo, useState, useTransition } from "react";
import { getKnowledgeMaterialsAction, getVisitKnowledgeMaterialsAction, pinKnowledgeMaterialToVisitAction, unpinKnowledgeMaterialFromVisitAction } from "../actions/knowledgeLibraryActions";
import type { KnowledgeMaterial, Visit } from "../domain";

export default function VisitKnowledgeMaterials({ visit }: { visit: Visit }) {
  const [allMaterials, setAllMaterials] = useState<KnowledgeMaterial[]>([]); const [selected, setSelected] = useState<KnowledgeMaterial[]>([]); const [query, setQuery] = useState(""); const [isPickerOpen, setIsPickerOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  useEffect(() => { let active = true; void Promise.all([getKnowledgeMaterialsAction(), getVisitKnowledgeMaterialsAction(visit.id)]).then(([materials, pinned]) => { if (active) { setAllMaterials(materials); setSelected(pinned); } }).catch(() => { if (active) setError("Materiały są chwilowo niedostępne."); }); return () => { active = false; }; }, [visit.id]);
  const available = useMemo(() => { const selectedIds = new Set(selected.map((item) => item.id)); const term = query.trim().toLocaleLowerCase("pl-PL"); return allMaterials.filter((item) => !selectedIds.has(item.id) && (!term || [item.title, item.category, ...item.tags].some((value) => value.toLocaleLowerCase("pl-PL").includes(term)))); }, [allMaterials, query, selected]);
  const pin = (material: KnowledgeMaterial) => startTransition(async () => { try { await pinKnowledgeMaterialToVisitAction(visit.id, material.id); setSelected((current) => [material, ...current]); setIsPickerOpen(false); setQuery(""); } catch { setError("Nie udało się przypiąć materiału."); } });
  const unpin = (material: KnowledgeMaterial) => startTransition(async () => { try { await unpinKnowledgeMaterialFromVisitAction(visit.id, material.id); setSelected((current) => current.filter((item) => item.id !== material.id)); } catch { setError("Nie udało się odpiąć materiału."); } });
  return <section className="rounded-2xl border border-[#D5DCCF] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#EEF1EB] p-2.5 text-[#6D7A62]"><BookOpen size={19} aria-hidden="true" /></span><div><h3 className="font-bold text-[#2D4739]">Polecane materiały</h3><p className="mt-1 text-sm text-gray-600">Ręcznie przypięte tylko do tej wizyty.</p></div></div><button type="button" onClick={() => setIsPickerOpen((current) => !current)} disabled={isPending} className="inline-flex items-center gap-2 rounded-xl border border-[#D5DCCF] px-3 py-2 text-sm font-semibold text-[#2D4739] hover:bg-[#EEF1EB]"><Plus size={16} aria-hidden="true" />Dodaj materiał</button></div>{isPickerOpen && <div className="mt-4 rounded-xl bg-[#F8F5F0] p-4"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Szukaj w bibliotece..." className="w-full rounded-xl border border-[#E5E1D8] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#6D7A62]" />{available.length === 0 ? <p className="mt-3 text-sm text-gray-500">Brak materiałów do dodania.</p> : <div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{available.map((material) => <button key={material.id} type="button" onClick={() => pin(material)} disabled={isPending} className="flex w-full items-center justify-between rounded-xl bg-white px-3 py-3 text-left text-sm hover:bg-[#EEF1EB]"><span><strong className="text-[#2D4739]">{material.title}</strong><span className="ml-2 text-gray-500">{material.category}</span></span><Pin size={15} className="text-[#B7791F]" aria-hidden="true" /></button>)}</div>}</div>}{error && <p className="mt-4 text-sm text-[#A35D3A]">{error}</p>}{selected.length === 0 ? <p className="mt-4 rounded-xl bg-[#F8F5F0] px-4 py-4 text-sm text-gray-600">Wybierz materiał z biblioteki, aby mieć go pod ręką przed spotkaniem.</p> : <div className="mt-4 space-y-3">{selected.map((material) => <article key={material.id} className="rounded-xl bg-[#F8F5F0] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#2D4739]">{material.title}</p><p className="mt-1 text-xs font-medium text-[#6D7A62]">{material.category}</p>{material.description && <p className="mt-2 text-sm text-gray-700">{material.description}</p>}</div><button type="button" onClick={() => unpin(material)} disabled={isPending} aria-label={`Odepnij ${material.title}`} className="rounded-lg p-2 text-gray-500 hover:bg-white"><X size={17} aria-hidden="true" /></button></div></article>)}</div>}<p className="mt-4 text-xs text-gray-500">TODO: w przyszłości AI może proponować materiały na podstawie tematu wizyty — bez automatycznych decyzji.</p></section>;
}
