"use client";

import { CheckCircle2, ClipboardCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getVisitBriefAction } from "../actions/visitBriefActions";
import { getVisitPlanTemplatesAction } from "../actions/visitPlanActions";
import type { Visit, VisitTemplate } from "../domain";
import type { VisitBriefData } from "../services/visitBriefService";
import { updateBooking } from "../services/bookingService";
import FollowupReminderForm from "./FollowupReminderForm";
import PatientNotes from "./patients/PatientNotes";
import PatientTasks from "./patients/PatientTasks";

export type WorkflowStep = "preparation" | "conversation" | "note" | "task" | "finish";
const steps: { id: WorkflowStep; label: string }[] = [{ id: "preparation", label: "Przygotowanie" }, { id: "conversation", label: "Rozmowa" }, { id: "note", label: "Notatka" }, { id: "task", label: "Zadanie" }, { id: "finish", label: "Koniec" }];

export function VisitWorkflowProgress({ activeStep }: { activeStep: WorkflowStep }) { const activeIndex = steps.findIndex((item) => item.id === activeStep); return <ol className="flex w-full overflow-x-auto pb-1">{steps.map((item, index) => <li key={item.id} className="flex min-w-[78px] flex-1 items-center"><span className="flex flex-col items-center gap-2 text-center"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${index <= activeIndex ? "bg-[#6D7A62] text-white" : "bg-[#E5E1D8] text-gray-500"}`}>{index < activeIndex ? "✓" : index + 1}</span><span className={`text-xs font-semibold ${index === activeIndex ? "text-[#2D4739]" : "text-gray-500"}`}>{item.label}</span></span>{index < steps.length - 1 && <span className={`mb-6 h-px flex-1 ${index < activeIndex ? "bg-[#6D7A62]" : "bg-[#E5E1D8]"}`} />}</li>)}</ol>; }

export default function VisitWorkflow({ visit }: { visit: Visit }) {
  const router = useRouter(); const [step, setStep] = useState<WorkflowStep>("preparation"); const [brief, setBrief] = useState<VisitBriefData | null>(null); const [templates, setTemplates] = useState<VisitTemplate[]>([]); const [noteSaved, setNoteSaved] = useState(false); const [taskSaved, setTaskSaved] = useState(false); const [isCompleting, setIsCompleting] = useState(false);
  useEffect(() => { if (!visit.patient_id) return; let active = true; void Promise.all([getVisitBriefAction(visit.patient_id, visit.id), getVisitPlanTemplatesAction()]).then(([data, loadedTemplates]) => { if (!active) return; setBrief(data); setTemplates(loadedTemplates); setNoteSaved(data.notes.length > 0); setTaskSaved(data.tasks.length > 0); }).catch(() => undefined); return () => { active = false; }; }, [visit.id, visit.patient_id]);
  if (!visit.patient_id) return null;
  const finish = async () => { setIsCompleting(true); try { await updateBooking(visit.id, "Zrealizowane"); router.refresh(); } finally { setIsCompleting(false); } };
  return <section className="mt-5 rounded-2xl border border-[#D5DCCF] bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#EEF1EB] p-2.5 text-[#6D7A62]"><ClipboardCheck size={19} aria-hidden="true" /></span><div><p className="text-sm text-gray-500">Proces pracy podczas spotkania</p><h3 className="font-bold text-[#2D4739]">Workflow wizyty</h3></div></div><div className="mt-5"><VisitWorkflowProgress activeStep={step} /></div>{step === "preparation" && <div className="mt-5 rounded-xl bg-[#F8F5F0] p-4"><p className="text-sm text-gray-700">Uruchom prosty tryb gabinetowy do prowadzenia aktualnego spotkania.</p><button type="button" onClick={() => router.push(`/panel/visits/${visit.id}/session`)} className="mt-4 rounded-xl bg-[#6D7A62] px-4 py-2.5 text-sm font-semibold text-white">▶ Rozpocznij wizytę</button></div>}{step === "conversation" && <button type="button" onClick={() => setStep("note")} className="mt-5 rounded-xl bg-[#6D7A62] px-4 py-2.5 text-sm font-semibold text-white">Przejdź do notatki</button>}{step === "note" && <PatientNotes patientId={visit.patient_id} notes={brief?.notes ?? []} templates={templates} onNoteSaved={() => { setNoteSaved(true); setStep("task"); }} />}{step === "task" && <PatientTasks patientId={visit.patient_id} tasks={brief?.tasks ?? []} onTaskSaved={() => { setTaskSaved(true); setStep("finish"); }} />}{step === "finish" && <div className="mt-5 rounded-xl bg-[#EEF1EB] p-5"><div className="flex items-center gap-3"><CheckCircle2 className="text-[#3E7C49]" size={24} /><h4 className="font-bold">Wizyta zakończona</h4></div><p className="mt-3 text-sm">Notatka: {noteSaved ? "✓" : "○"} · Zadanie: {taskSaved ? "✓" : "○"} · Kolejna wizyta: {brief?.hasNextVisit ? "✓" : "○"}</p><div className="mt-4"><FollowupReminderForm patientId={visit.patient_id} visitId={visit.id} /></div><button type="button" onClick={finish} disabled={isCompleting} className="mt-4 rounded-xl bg-[#6D7A62] px-4 py-2.5 text-sm font-semibold text-white">{isCompleting ? "Zapisywanie..." : "Zakończ wizytę"}</button></div>}<div className="mt-4 flex gap-2"><button type="button" onClick={() => setStep("conversation")} className="text-sm font-semibold text-[#6D7A62]">Rozmowa</button><button type="button" onClick={() => setStep("note")} className="text-sm font-semibold text-[#6D7A62]">Notatka</button></div><p className="mt-5 text-xs text-gray-500">TODO: świadomie uruchamiane wysyłanie materiałów, zadań domowych i prośby o opinię Google.</p></section>;
}
